-- Synthetic commercial state only; all fixtures are rolled back.
begin;
create extension if not exists pgtap with schema extensions;
select plan(91);
create function pg_temp.plan_id(n integer) returns uuid language sql immutable as $$
  select ('eeee0035-0000-4000-8000-' || lpad(n::text,12,'0'))::uuid
$$;
create temp table existing_tenants as select id, to_jsonb(b) as snapshot from public.barbershops b;
insert into public.barbershops(id,name,slug) values
(pg_temp.plan_id(1),'Plan fixture A','plan-foundation-a'),
(pg_temp.plan_id(2),'Plan fixture B','plan-foundation-b');
insert into auth.users(id,aud,role,email,raw_user_meta_data) values
(pg_temp.plan_id(101),'authenticated','authenticated','plan-owner@example.test','{"role":"owner"}');
update public.profiles set barbershop_id=pg_temp.plan_id(1) where id=pg_temp.plan_id(101);
select has_table('public','commercial_plans','commercial_plans exists');
select ok((select relrowsecurity from pg_class where oid='public.commercial_plans'::regclass),'commercial_plans enables RLS');
select is((select count(*) from pg_policies where schemaname='public' and tablename='commercial_plans'),0::bigint,'commercial_plans has no permissive policies');
select ok(not exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a where c.oid='public.commercial_plans'::regclass and a.grantee=0),'commercial_plans: no PUBLIC ACL');
select ok(not exists(select 1 from pg_attribute a cross join lateral aclexplode(a.attacl) x where a.attrelid='public.commercial_plans'::regclass and x.grantee=0),'commercial_plans: no PUBLIC column ACL');
select has_table('public','tenant_subscriptions','tenant_subscriptions exists');
select ok((select relrowsecurity from pg_class where oid='public.tenant_subscriptions'::regclass),'tenant_subscriptions enables RLS');
select is((select count(*) from pg_policies where schemaname='public' and tablename='tenant_subscriptions'),0::bigint,'tenant_subscriptions has no permissive policies');
select ok(not exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a where c.oid='public.tenant_subscriptions'::regclass and a.grantee=0),'tenant_subscriptions: no PUBLIC ACL');
select ok(not exists(select 1 from pg_attribute a cross join lateral aclexplode(a.attacl) x where a.attrelid='public.tenant_subscriptions'::regclass and x.grantee=0),'tenant_subscriptions: no PUBLIC column ACL');
select is((select count(*) from public.tenant_subscriptions where barbershop_id in (pg_temp.plan_id(1),pg_temp.plan_id(2))),0::bigint,'tenant creation does not silently assign a plan or trial');
select lives_ok($$insert into public.commercial_plans(code,name) values('fixture_v1','Fixture plan')$$,'trusted catalog creation works');
select throws_ok($$insert into public.commercial_plans(code,name) values('','Fixture')$$,'23514',null,'rejects empty code');
select throws_ok($$insert into public.commercial_plans(code,name) values('UPPER','Fixture')$$,'23514',null,'rejects uppercase code');
select throws_ok($$insert into public.commercial_plans(code,name) values('paid-plan','Fixture')$$,'23514',null,'rejects noncanonical code');
select throws_ok($$insert into public.commercial_plans(code,name) values(repeat('a',65),'Fixture')$$,'23514',null,'rejects overlong code');
select throws_ok($$insert into public.commercial_plans(code,name) values('empty_name',' ')$$,'23514',null,'rejects blank name');
select throws_ok($$insert into public.commercial_plans(code,name) values('fixture_v1','Duplicate')$$,'23505',null,'plan identity is unique');
select lives_ok($$insert into public.tenant_subscriptions(barbershop_id,plan_code,status,created_at,updated_at) values(pg_temp.plan_id(1),'fixture_v1','active',now()-interval '1 day',now()-interval '1 day')$$,'active subscription may have no billing period or trial');
select lives_ok($$insert into public.tenant_subscriptions(barbershop_id,plan_code,status) values(pg_temp.plan_id(2),'fixture_v1','pending')$$,'another tenant may reference the same plan');
select throws_ok($$insert into public.tenant_subscriptions(barbershop_id,plan_code,status) values(pg_temp.plan_id(1),'fixture_v1','canceled')$$,'23505',null,'at most one current state per tenant regardless of status');
select throws_ok($$insert into public.tenant_subscriptions(barbershop_id,plan_code,status) values(pg_temp.plan_id(999),'fixture_v1','active')$$,'23503',null,'tenant FK rejects orphan subscription');
select throws_ok($$update public.tenant_subscriptions set plan_code='missing' where barbershop_id=pg_temp.plan_id(1)$$,'23503',null,'rejects unknown plan');
select throws_ok($$update public.tenant_subscriptions set plan_code=null where barbershop_id=pg_temp.plan_id(1)$$,'23502',null,'rejects null plan');
select throws_ok($$update public.tenant_subscriptions set status='paid' where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects unknown status');
select throws_ok($$update public.tenant_subscriptions set status=null where barbershop_id=pg_temp.plan_id(1)$$,'23502',null,'rejects null status');
select throws_ok($$update public.tenant_subscriptions set status='trialing' where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects trialing without dates');
select throws_ok($$update public.tenant_subscriptions set trial_started_at=now() where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects trial start without end');
select throws_ok($$update public.tenant_subscriptions set trial_ends_at=now() where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects trial end without start');
select throws_ok($$update public.tenant_subscriptions set trial_started_at=now(),trial_ends_at=now() where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects zero trial interval');
select throws_ok($$update public.tenant_subscriptions set trial_started_at=now(),trial_ends_at=now()-interval '1 day' where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects reversed trial interval');
select throws_ok($$update public.tenant_subscriptions set trial_started_at=now(),trial_ends_at='infinity' where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects infinite trial');
select throws_ok($$update public.tenant_subscriptions set current_period_started_at=now() where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects period start without end');
select throws_ok($$update public.tenant_subscriptions set current_period_ends_at=now() where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects period end without start');
select throws_ok($$update public.tenant_subscriptions set current_period_started_at=now(),current_period_ends_at=now() where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects zero cycle');
select throws_ok($$update public.tenant_subscriptions set current_period_started_at=now(),current_period_ends_at=now()-interval '1 day' where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects reversed cycle');
select throws_ok($$update public.tenant_subscriptions set current_period_started_at='-infinity',current_period_ends_at=now() where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects infinite cycle');
select throws_ok($$update public.tenant_subscriptions set created_at='infinity' where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects infinite creation');
select throws_ok($$update public.tenant_subscriptions set created_at=now()+interval '1 day' where barbershop_id=pg_temp.plan_id(1)$$,'23514',null,'rejects updated before created');
select throws_ok($$delete from public.commercial_plans where code='fixture_v1'$$,'23503',null,'referenced plan cannot be deleted');
select throws_ok($$update public.commercial_plans set code='renamed' where code='fixture_v1'$$,'23503',null,'referenced identity cannot be renamed');
select lives_ok($$update public.tenant_subscriptions set status='trialing',trial_started_at=now(),trial_ends_at=now()+interval '7 days' where barbershop_id=pg_temp.plan_id(1)$$,'explicit finite trial works without a fixed commercial duration');
select lives_ok($$update public.tenant_subscriptions set current_period_started_at=now(),current_period_ends_at=now()+interval '15 days' where barbershop_id=pg_temp.plan_id(1)$$,'explicit period works without assuming monthly recurrence');
select lives_ok($$update public.tenant_subscriptions set status='pending' where barbershop_id=pg_temp.plan_id(1)$$,'pending is an allowed commercial state');
select lives_ok($$update public.tenant_subscriptions set status='active' where barbershop_id=pg_temp.plan_id(1)$$,'active is an allowed commercial state');
select lives_ok($$update public.tenant_subscriptions set status='paused' where barbershop_id=pg_temp.plan_id(1)$$,'paused is an allowed commercial state');
select lives_ok($$update public.tenant_subscriptions set status='canceled' where barbershop_id=pg_temp.plan_id(1)$$,'canceled is an allowed commercial state');
select is((select updated_at from public.tenant_subscriptions where barbershop_id=pg_temp.plan_id(1)),now(),'subscription updates use existing transaction timestamp trigger');
select ok((select created_at=now()-interval '1 day' from public.tenant_subscriptions where barbershop_id=pg_temp.plan_id(1)),'subscription creation timestamp survives updates');
update public.commercial_plans set name='Updated fixture' where code='fixture_v1';
select is((select updated_at from public.commercial_plans where code='fixture_v1'),now(),'catalog timestamp trigger works');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.plan_id(101),'role','authenticated')::text,true);
select ok(not has_table_privilege('anon','public.commercial_plans','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon: no commercial_plans table access');
select ok(not has_any_column_privilege('anon','public.commercial_plans','SELECT,INSERT,UPDATE,REFERENCES'),'anon: no commercial_plans column access');
select ok(not has_table_privilege('anon','public.tenant_subscriptions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'anon: no tenant_subscriptions table access');
select ok(not has_any_column_privilege('anon','public.tenant_subscriptions','SELECT,INSERT,UPDATE,REFERENCES'),'anon: no tenant_subscriptions column access');
set local role anon;
select throws_ok($$select * from public.commercial_plans$$,'42501',null,'anon cannot read commercial_plans');
select throws_ok($$insert into public.commercial_plans default values$$,'42501',null,'anon cannot insert commercial_plans');
select throws_ok($$update public.commercial_plans set updated_at=now()$$,'42501',null,'anon cannot update commercial_plans');
select throws_ok($$delete from public.commercial_plans$$,'42501',null,'anon cannot delete commercial_plans');
select throws_ok($$select * from public.tenant_subscriptions$$,'42501',null,'anon cannot read tenant_subscriptions');
select throws_ok($$insert into public.tenant_subscriptions default values$$,'42501',null,'anon cannot insert tenant_subscriptions');
select throws_ok($$update public.tenant_subscriptions set updated_at=now()$$,'42501',null,'anon cannot update tenant_subscriptions');
select throws_ok($$delete from public.tenant_subscriptions$$,'42501',null,'anon cannot delete tenant_subscriptions');
reset role;
select ok(not has_table_privilege('authenticated','public.commercial_plans','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated: no commercial_plans table access');
select ok(not has_any_column_privilege('authenticated','public.commercial_plans','SELECT,INSERT,UPDATE,REFERENCES'),'authenticated: no commercial_plans column access');
select ok(not has_table_privilege('authenticated','public.tenant_subscriptions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'authenticated: no tenant_subscriptions table access');
select ok(not has_any_column_privilege('authenticated','public.tenant_subscriptions','SELECT,INSERT,UPDATE,REFERENCES'),'authenticated: no tenant_subscriptions column access');
set local role authenticated;
select throws_ok($$select * from public.commercial_plans$$,'42501',null,'authenticated cannot read commercial_plans');
select throws_ok($$insert into public.commercial_plans default values$$,'42501',null,'authenticated cannot insert commercial_plans');
select throws_ok($$update public.commercial_plans set updated_at=now()$$,'42501',null,'authenticated cannot update commercial_plans');
select throws_ok($$delete from public.commercial_plans$$,'42501',null,'authenticated cannot delete commercial_plans');
select throws_ok($$select * from public.tenant_subscriptions$$,'42501',null,'authenticated cannot read tenant_subscriptions');
select throws_ok($$insert into public.tenant_subscriptions default values$$,'42501',null,'authenticated cannot insert tenant_subscriptions');
select throws_ok($$update public.tenant_subscriptions set updated_at=now()$$,'42501',null,'authenticated cannot update tenant_subscriptions');
select throws_ok($$delete from public.tenant_subscriptions$$,'42501',null,'authenticated cannot delete tenant_subscriptions');
reset role;
select ok(not has_table_privilege('service_role','public.commercial_plans','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role: no commercial_plans table access');
select ok(not has_any_column_privilege('service_role','public.commercial_plans','SELECT,INSERT,UPDATE,REFERENCES'),'service_role: no commercial_plans column access');
select ok(not has_table_privilege('service_role','public.tenant_subscriptions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'),'service_role: no tenant_subscriptions table access');
select ok(not has_any_column_privilege('service_role','public.tenant_subscriptions','SELECT,INSERT,UPDATE,REFERENCES'),'service_role: no tenant_subscriptions column access');
set local role service_role;
select throws_ok($$select * from public.commercial_plans$$,'42501',null,'service_role cannot read commercial_plans');
select throws_ok($$insert into public.commercial_plans default values$$,'42501',null,'service_role cannot insert commercial_plans');
select throws_ok($$update public.commercial_plans set updated_at=now()$$,'42501',null,'service_role cannot update commercial_plans');
select throws_ok($$delete from public.commercial_plans$$,'42501',null,'service_role cannot delete commercial_plans');
select throws_ok($$select * from public.tenant_subscriptions$$,'42501',null,'service_role cannot read tenant_subscriptions');
select throws_ok($$insert into public.tenant_subscriptions default values$$,'42501',null,'service_role cannot insert tenant_subscriptions');
select throws_ok($$update public.tenant_subscriptions set updated_at=now()$$,'42501',null,'service_role cannot update tenant_subscriptions');
select throws_ok($$delete from public.tenant_subscriptions$$,'42501',null,'service_role cannot delete tenant_subscriptions');
reset role;
select ok((select active from public.barbershops where id=pg_temp.plan_id(1)),'canceled commercial state does not disable tenant');
select ok((select active and role='owner' and barbershop_id=pg_temp.plan_id(1) from public.profiles where id=pg_temp.plan_id(101)),'commercial state does not change owner access/profile');
select is((select count(*) from public.tenant_subscriptions where barbershop_id in (pg_temp.plan_id(1),pg_temp.plan_id(2))),2::bigint,'API mutation attempts changed no subscription rows');
select ok(not exists(select 1 from existing_tenants e full join public.barbershops b on b.id=e.id where (e.id is not null or b.id not in (pg_temp.plan_id(1),pg_temp.plan_id(2))) and e.snapshot is distinct from to_jsonb(b)),'existing tenant records remain unchanged');
select ok(not has_table_privilege('authenticated','public.appointments','SELECT,INSERT,UPDATE,DELETE'),'operational direct appointment privileges remain closed');
select * from finish();
rollback;
